import React from "react";
import bg3 from "../../assets/home/bg-3.jpg"
import Head from "next/head";

const termsAndConditions: React.FC = () => {
  return (<>
    <Head>
    <title>SavingSathi Terms & Conditions | User Agreement & Policies</title>
    <meta 
      name="description" 
      content="Understand SavingSathi’s user terms, how pairing with a Sathi works, offer redemption policies, account rules, and other important legal guidelines." 
    />
    <meta property="og:title" content="SavingSathi Terms & Conditions | User Agreement & Policies" />
    <meta 
      property="og:description" 
      content="Understand SavingSathi’s user terms, how pairing with a Sathi works, offer redemption policies, account rules, and other important legal guidelines." 
    />
   
    <link rel="canonical" href="https://savingsathi.com/terms-and-conditions" />
  </Head>
    <section className="bg-black text-white min-h-screen">
      {/* Header */}
      <div
        className="w-full h-70 flex justify-center items-center bg-cover bg-center relative"
        style={{
            backgroundImage:`url(${bg3.src})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundAttachment: "fixed"
          }}
      >
        <h1 className="text-4xl font-extrabold text-center tracking-wider z-10">
          <span className="text-white uppercase">TERMS And </span>
          <span className="bg-gradient-to-r from-rose-600 to-cyan-700 bg-clip-text text-transparent uppercase">Conditions</span>
        </h1>
      </div>

      {/* Content */}
      <div className="max-w-6xl mx-auto mt-16 md:px-0 px-4">
        <div className="text-gray-300 space-y-6">
          <p>
            This is an agreement between you ("you" or "your") and SavingSathi Global Services Private Limited (“Company, SavingSathi, The Company, us, our”), a company registered under the Companies Act 2013 with its registered office and corporate office at 233, Opp Sunny Trade Centre, New Aatish Market , Sanganer Jaipur- 302020,that governs your use of the search services offered by SavingSathi through its Website/App and / or other virtual medium, telephone search, SMS, WAP, APP or any other medium using which Company may provide the search services (collectively "Platforms" ). When you access or use any of the Platforms you agree to be bound by these Terms and Conditions ("Terms, T&C").
          </p>

          <p>
            This document is an electronic record in accordance of provisions of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended time to time by the legislature in the Information Technology Act, 2000 or made any enactment. This electronic record is generated by a computer system anddoes not require any physical or digital signatures. By registering at Our Site/App App as a Merchant and usingthe Services, You shall be contracting with SavingSathi Global Services Private Limited. You agree to be bound by the T&Cs and allpolicies and guidelines of the Site are herein incorporated by reference.
          </p>

          <p>
            These Terms of Use ("Agreement") describe the terms and conditions applicable to your access and use of the Website/App www.SavingSathi.com(the "Site") and Application. Please ensure that you (referred to as the "User", "you" or "your") read these TERMS AND CONDITIONS OF USE with care as they govern your use of and access to this Website/App (also referred to as "Site").
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-white">Application and Acceptance of the Terms</h2>
          <p>
            Your use of the Sites and SavingSathi's services is subject to the terms and conditions contained in this document as well as the Privacy Policy and any other rules and policies of the Sites that companymay publish from time to time. This document and such other rules and policies of the Sites are collectively referred to below as the "Terms".
          </p>

          <p>
            BY ACCESSING THE SITE/APP APP OR USING THE SERVICES, YOU AGREE TO ACCEPT AND BE BOUND BY THE TERMS.  PLEASE DO NOT USE THE SERVICES OR THE SITES IF YOU DO NOT ACCEPT ALL THE TERMS. YOUR REMEDY FOR DISSATISFACTION WITH THIS SITE, SERVICES, CONTENT, OR OTHER INFORMATION AVAILABLE ON OR THROUGH THIS SITE, IS TO STOP USING THE SITE AND/OR THOSE SERVICES. YOUR AGREEMENT WITH US REGARDING COMPLIANCE WITH THESE TERMS & CONDITIONS OF USE BECOMES EFFECTIVE IMMEDIATELY UPON COMMENCEMENT OF YOUR USE OF THIS SITE.
          </p>

          <p>
            We expressly reserve the right to change these Terms & Conditions of Use from time to time without any further notice to you. You acknowledge and agree that it is your responsibility to review this site/App and these Terms of Use from time to time and to familiarize yourself with any modifications/ amendments. We also reserve the sole right to either modify or discontinue the site, including any of the sites features, at any time with or without any notice to you. We will not be liable to you or any third party while exercising such right. Any new features that augment or enhance the current services on this site shall also be subject to these Terms & Conditions of Use.
          </p>

          <p>
            SavingSathi is not responsible of the manner in which you use the information published on our Website/App, while we continuously strive to maintain the quality, safety and accuracy levels of all information on SavingSathi.We do not provide any guarantee about the person with whom you are connecting/sharing/discussing/meeting/dating/ for your purposes. Please use your best practices / way/ knowledge/ mind to find out the best person/ post /deal/ option for you and for your purpose. We do not provide any guarantee or warranty about the completeness, accuracy, punctuality or suitability of the same. By using our resources, you are acknowledging that there can be errors/inaccuracies in the content provided by other users. SavingSathi, however, cannot be held liable for such errors.
          </p>

          <p>
            In case of a dispute that may arise between the users (service provider/service receiver/seller/buyer/vendor /customer) in respect to the payment/transaction and, there remains no scope for mutual resolution or amicable settlement, then the disputed amount parked with " SavingSathi shall be transferred in the account of SavingSathi Global Services Private Limited if payment made by using SavingSathi's payment gateway otherwise we are not responsible for any monetary transactions happened between users . We are only the platform who are connecting the people for their need/interest/purpose.
          </p>

          <p>
            Further,SavingSathi shall try to meditate/conciliate the dispute between the users and release the payment post settlement.
          </p>

          <p>
            SavingSathishall not be liable to pay any interest for the disputed amount for the period it is parked in its account.
          </p>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">1. Definitions</h3>
            <p className="mb-4">The terms in these T&C shall be defined as below:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>"Applicable Laws" shall mean and include all applicable Statutes, enactments, Acts of Legislature or the Parliament, Laws, Ordinances, Rules, By-laws, Regulations, Notifications, Guidelines, Policies, Directions, Directives and Orders of any Governmental Authority, Tribunal, Board, or a Court.</li>
              <li>"Companies Act/ Company Law"shall mean Companies Act, 2013 and rules made there under for the time being in force, as amended time to time.</li>
              <li>"User"shall mean users of Website/App and registered for obtaining/receiving services and / or benefits.</li>
              <li>"SavingSathi"shall be referred as SavingSathi Global Services Private Limited.</li>
              <li>"Merchant"shall mean an individual or company or firm or any other business entity listed and avail paid services.</li>
              <li>"Merchant Account"refers to the account created by merchant with SavingSathi.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">2. Interpretation</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">(a)</span> Any reference to the singular includes a reference to the plural and vice versa, unless explicitlyprovided for otherwise; and any reference to the masculine includes a reference to the feminineand vice versa.</li>
              <li><span className="font-bold">(b)</span> Headings and captions are used for convenience only and will not affect the interpretation ofthese T&Cs.</li>
              <li><span className="font-bold">(c)</span> Any reference to a natural person will, unless repugnant to the context, include his heirs, executors and permitted assignees</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">3. Merchant/User Eligibility</h3>
            <p className="mb-4">No Individual / organization shallbe eligible to be registered as user/ merchant, if:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">(a)</span> Individual has/have not attained 18(Eighteen) years of age or</li>
              <li><span className="font-bold">(b)</span> can lawfully enter into and form contracts under Applicable Laws and have all requisite right, power and authority to perform Your obligations as a Merchant;</li>
              <li><span className="font-bold">(c)</span> Deals in any of the goods and services listed in Schedule I, which are banned under Applicable Laws ("Banned Goods/Services").</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">4. Registered User</h3>
            <p>
              While you can scroll through the Platform without registering with us but a registered user can use/avail the services/products of website /application. To become a registered User(s) of the Website/App a proper procedure has been made available on the Website/App which is for the convenience of User(s) so that they can easily use the Website/App.
            </p>
            <p className="mt-4">
              User(s) can become registered User(s) by filling an on-line registration form on the Website/App by providing the required information (including name, contact information, details of User(s) business, interest, profession etc.). SavingSathi will establish an account ("Account") for the User(s) upon successful registration. Company may at its sole discretion assign to User(s) upon registration a web-based email or messaging account ("Email Account") with limited storage space to send or receive emails or messages. Users will be responsible for the content of all the messages communicated through the account.User may also link his phone number with his SavingSathi's Account. We may use your phone number or any other mode to verify your account.
            </p>
            <p className="mt-4">
              User(s) registering on the Website/App on behalf of business entities represent and warrant that: (a) they have the requisite authority to bind such business entity this Agreement; (b) the address provided by such User(s) at the time of registration is the principal place of business of such business entity; and (c) all other information provided to SavingSathi, during the registration process is true, accurate, current and complete. For purposes of this provision, a branch or representative office of a User(s) will not be considered a separate entity and the principal place of business of the User(s) will be deemed to be that of its head office.
            </p>
            <p className="mt-4">
              User(s) agree that by registering on the Website/App, they consent to the inclusion of their personal data in SavingSathi's on-line database and authorize SavingSathi to share such information with other User(s) when required for better services after considering the sensitivity of information. SavingSathi may refuse registration of any User(s) for whatever reason. Further, SavingSathi may suspend or terminate a registered membership at any time without any prior notification of the interest of the company or general interest of its User(s) without assigning any reason thereof and there shall arise no further liability on SavingSathi of whatsoever nature due to the suspension or termination of the User account. User(s) registered on the Website/App are in no manner a part of or affiliated to SavingSathi.
            </p>
            <p className="mt-4">
              User(s) further agree and consent to be contacted by SavingSathi through phone calls, SMS notifications or any other means of communication, in respect to the services provided by company even if contact number(s) provided to company upon registration are on Do Not Call Registry.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">5. User's Agreement</h3>
            <p>
              This Agreement applies to any person who accesses or uses the Website/App for any purpose. It also applies to any legal entity which may be represented by any person who accesses or uses the Website/App, under actual or apparent authority. User(s) may use this Website/App solely for their commercial/business/personal/same interest/post/opinion purposes.
            </p>
            <p className="mt-4">
              This Agreement applies to all services offered on the Website/App and by Company, collectively with any additional terms and conditions that may be applicable in respect of any specific service used or accessed by User(s) on the Website/App. In the event of any conflict or inconsistency between any provision of this Agreement and any additional terms and conditions applicable in respect of any service offered on the Website/App, such additional terms and conditions applicable in respect of that service shall prevail over this Agreement.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">6. Amendment to User(s) Agreement</h3>
            <p>
              SavingSathi reserves the right to change, modify, amend, or update the Agreement from time to time and such amended provisions of the Agreement shall be effective immediately upon being posted on the Website/App. If you do not agree to such provisions, you must stop using the service with immediate effect. Your continuous use of the service will be deemed to signify your acceptance of the amended provisions of the Agreement.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">7. Intellectual Property Rights</h3>
            <p>
              SavingSathi is the sole owner and the lawful licensee of all the rights to the Website/App and its content("Website/App Content"). Website/App Content means the design, layout, text, images, graphics, sound, video etc. of or made available on the Website/App. The Website/App Content embodies trade secrets and other intellectual property rights protected under worldwide copyright and other applicable laws pertaining to intellectual property. All title, ownership and intellectual property rights in the Website/App and the Website/App Content shall remain in SavingSathi, its affiliates or licensor's of the Website/App content, as the case may be.
            </p>
            <p className="mt-4">
              All rights, not otherwise claimed under this Agreement by SavingSathi, are hereby reserved. Any information or advertisements contained on, distributed through, or linked, downloaded or accessed from any of the services contained on the Website/App or any offer displayed on or in connection with any service offered on the Website/App ("Website/App Information")is intended, solely to provide general information for the personal use of the User(s), who fully accept and all responsibility and liabilities arising from and out of the use of such Information. SavingSathi does not represent, warrant or endorse in any manner the accuracy or reliability of Website/Appinformation, or the quality of any products and/or services obtained by the User(s) as a result of any Website/AppInformation.
            </p>
            <p className="mt-4">
              The Information is provided "as is" with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of the Information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing contained in the Agreement shall to any extent substitute for the independent investigations and the sound technical, personal and business judgment of the User(s). In no event shall SavingSathi be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to SavingSathi's Services. User(s) hereby acknowledge that any reliance upon the Information shall be at their sole risk and further understand and acknowledge that the Information has been compiled from publicly aired and published sources. SavingSathi respects the rights of such entities and cannot be deemed to be infringing on the respective copyrights or businesses of such entities. SavingSathi reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in any portion ofthe Information.
            </p>
            <p className="mt-4">
              Any promotional content, offers, reviews, or mentions of third-party brands and vendors shared by users on the SavingSathi Platform are purely user-submitted and do not imply any partnership, sponsorship, affiliation, or endorsement by SavingSathi. All third-party brand names, trademarks, logos, and content mentioned on the Platform are the property of their respective owners.
            </p>
            <p className="mt-4">
              If any person or entity believes that content posted on the Platform violates their intellectual property rights or misrepresents their brand, they may contact us at support@SavingSathi.com or submit a request through the designated grievance section of our website/app. SavingSathi will promptly review and take appropriate action in accordance with applicable laws.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Trademark</h4>
            <p>
              "SavingSathi" and related icons and logos are/will be registered trademarks or trademarks or service marks of SavingSathi in various jurisdictions and are/will be protected under applicable copyright, trademark and other proprietary and intellectual property rights laws. The unauthorized adoption copying, modification, use or publication of these marks is strictly prohibited.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Copyright</h4>
            <p>
              All Website/App Content including Website/App Information is/will be copyrighted to SavingSathi excluding any third-party content and any links to any third-party Website/App s being made available or contained on the Website/App. User(s) may not use any trademark, service mark or logo of any independent third parties without prior written approval from such parties.
            </p>
            <p className="mt-4">
              User(s) acknowledge and agree that SavingSathi is not an arbiter or judge of disputes concerning intellectual property rights and as such cannot verify that User(s) selling or supplying merchandise or providing services/posting/sharing information/sharing content on the Website/App have the right to sell the merchandise or provide the services offered by such User(s). SavingSathi encourages User(s) to assist SavingSathi in identifying listings on the Website/App which in the User(s) knowledge or belief infringe their rights. User(s) further acknowledge and agree by taking down a listing, SavingSathi does not and cannot be deemed to be endorsing a claim of infringement and further that in those instances in which SavingSathi declines to take down a listing, SavingSathi does not and cannot be deemed to be endorsing that the listing is not infringing of third party's rights or endorsing any sale or supply of merchandise or services pursuant to or on account of such listing.
            </p>
            <p className="mt-4">
              SavingSathi respects the intellectual property rights of others, and we expect our User(s) to do the same. User(s) agree to not copy, download or reproduce the Website/App Content, Information or any other material, text, images, video clips, directories, files, databases or listings available on or through the Website/App for the purpose of re-selling or re-distributing, mass mailing (via email, wireless text messages, physical mail or otherwise) operating a business competing with company, or otherwise commercially exploiting the SavingSathi Content unless otherwise agreed between the parties. Systematic retrieval of SavingSathi Content to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from SavingSathi is prohibited.
            </p>
            <p className="mt-4">
              In addition, use of the SavingSathi Content for any purpose not expressly permitted in this Agreement is prohibited and entitles SavingSathi to initiate appropriate legal action. User(s) agree that as a condition of their access to and use of SavingSathi 's Services, they will not use SavingSathi 'sServices to infringe the intellectual property rights of any third parties in any way. SavingSathi reserves the right to terminate the right of any User(s) to access or use SavingSathi 'sServices for any infringement of the rights of third parties in conjunction with use of the SavingSathi s Service, or in the event SavingSathi is of the believes that User(s) conduct is prejudicial to the interests of SavingSathi, its affiliates, or other User(s), or for any other reason, atSavingSathi 's sole discretion, with or without cause.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">URL's/Sub-Domain</h4>
            <p>
              URL's/ Sub-domain names assigned by SavingSathi to User(s) (including both paid and free User(s)) are the exclusive property of SavingSathi and it cannot be assumed to be permanent in any case. SavingSathi reserves the right, without prior notice, at any point of time, to suspend or terminate or restrict access to or edit any URL's/Sub-domain names. IN ALL SUCH CASES, SavingSathi WILL NOT BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL DAMAGES, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION OR OTHERWISE. SavingSathi may allow User(s) access to content, products or services offered by third parties through hyperlinks (in the form of word link, banners, channels or otherwise) to the Website/App s offered by such third parties("Third Party Website/App s"). Company advises its User(s) to read the terms and conditions of use and/or privacy policies applicable in respect of such Third Party Website/App s prior to using or accessing such Third Party Website/App s. Users acknowledge and agree that SavingSathi has no control over any content offered on Third Party Website/App s, does not monitor such Third Party Website/App s, and shall in no manner be deemed to be liable or responsible to any person for such Third Party Sites, or any content, products or services made available thereof.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">8. Safety and security</h3>
            <p className="mb-4">During your connection/interaction/discussion with other users on the SavingSathi Platform, you agree to follow the following terms always:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">(a)</span> You will not post any unauthorized/ illegal/adult commercial/content/ communications (such as spam) on SavingSathi website/application or on any other medium.</li>
              <li><span className="font-bold">(b)</span> You will not engage in unlawful multi-level marketing, such as a pyramid scheme, on SavingSathi.</li>
              <li><span className="font-bold">(c)</span> You will not upload viruses or other malicious code that effect the SavingSathi app/website and other virtual mode.</li>
              <li><span className="font-bold">(d)</span> You will not bully, intimidate, or harass any user.</li>
              <li><span className="font-bold">(e)</span> You will not post content that: is hate speech, threatening, or pornographic; incites violence; or contains nudity or graphic or gratuitous violence.</li>
              <li><span className="font-bold">(f)</span> You will follow our Promotions Guidelines and all applicable laws if you publicize or offer any contest, giveaway, or sweepstakes ("promotion") on SavingSathi.</li>
              <li><span className="font-bold">(g)</span> You will not use SavingSathi to do anything unlawful, misleading, malicious, or discriminatory act.</li>
              <li><span className="font-bold">(h)</span> You will not do anything that could disable, overburden, or impair the proper working or appearance of SavingSathi, such as a denial-of-service attack or interference with page rendering or other SavingSathi functionality.</li>
              <li><span className="font-bold">(i)</span> You will not facilitate or encourage any violations of this Statement or our policies.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">9. Prohibited Content:</h3>
            <p className="mb-4">
              We endeavour to preserve the sanctity of the Platform and we strive to ensure that the User Content posted on the Platform is not harmful to our community, or contrary to law. Without limiting the generality of the foregoing, the following is an indicative list of the types of User Content that the Company deems to be inappropriate:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Content that belongs to another person and to which the user does not have any right;</li>
              <li>Content that is defamatory or libellous;</li>
              <li>Content that is obscene, pornographic, paedophilic, disrespectful, invasive of another's privacy, including bodily privacy, insulting or harassing based on gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;</li>
              <li>Content that is harmful to a person below the age of 18 years;</li>
              <li>Content that infringes any patent, trademark, copyright or other proprietary rights;</li>
              <li>Content that violates any law for the time being in force;</li>
              <li>Content that deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;</li>
              <li>Content that impersonates another person;</li>
              <li>Content that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;</li>
              <li>Content that contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of the Platform;</li>
              <li>Content that is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;</li>
              <li>Content that contains any abusive, or explicit language;</li>
              <li>Content that involves the transmission of "junk mail," "chain letters," or unsolicited mass mailing, instant messaging, "spimming," or "spamming";</li>
              <li>Content that contains restricted or password-only access pages or hidden pages or images (those not linked to or from another accessible page);</li>
              <li>Content that furthers or promotes any criminal activity or enterprise or provides instructional information about illegal activities including, but not limited to violating someone's privacy;</li>
              <li>Content that involves commercial activities and/or sales without our prior consent such as contests, sweepstakes, barter, advertising, or pyramid schemes;</li>
              <li>Content that solicits passwords or personal identifying information for commercial or unlawful purposes from other users.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">10. Security Breach:</h3>
            <p>
              If you know or have reasons to believe that the security of your SavingSathi's Account has been breached, you should report it on our Platform or contact our grievance officer immediately as per the contact information provided in Section 16 (Grievance Officer). If we find a security breach or suspected security breach of your SavingSathi's Account, we may require you to change your password, and/or temporarily or permanently block your SavingSathi Account without us incurring any liability.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">11. Limited License</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">a)</span> We grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and make personal and non-commercial use of the Platform.</li>
              <li><span className="font-bold">b)</span> You do not have any permission to download, copy, install, reverse-engineer or use the Platform, or information made available on the Platform for any other purpose without our prior written consent. All rights not expressly granted to you in these Terms are reserved and retained by us. We reserve the right, at our sole discretion and at any time, without notice, to terminate your license to use the Platform and prevent your future access to the Platform.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">12. Restriction on use</h3>
            <p className="mb-4">
              You agree and undertake that by using the Platform you shall not engage in or encourage or assist others to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Post any Content that may amount to Prohibited Content as defined above;</li>
              <li>Use the Platform or any content or information for any purpose or in any manner that is illegal or prohibited by these Terms or under any applicable laws;</li>
              <li>Use the Platform for any harmful or nefarious purpose;</li>
              <li>Use the Platform in order to cause any kind of damage to us in any form or manner whatsoever;</li>
              <li>work around any technical limitations in the software provided to you as part of the services on the Platform;</li>
              <li>probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures;</li>
              <li>modify, translate, create derivate works, reverse engineer, decompile or disassemble the software, except and only to the extent that applicable law expressly permits;</li>
              <li>Directly or indirectly disclose your real identity (including any information that could lead to exposure of your real identity), in any manner whatsoever, either on the Platform or outside;</li>
              <li>Directly or indirectly, publish, post or disclose or threaten to disclose, or incentivize others to disclose, in any manner whatsoever, other users' private information (including their real identity or any information that could lead to exposure of their real identity);</li>
              <li>Spam or defraud any users of the Platform or any potential users thereof;</li>
              <li>Impersonate any person or entity on the Platform;</li>
              <li>Be disrespectful or unkind while interacting or communicating with any of our representatives, including without limitation, our grievance officer;</li>
              <li>Use the Platform or any content or information thereof in any manner that violates or infringes anyone's rights, including rights of publicity, privacy, copyright, trademark or other intellectual property or contractual rights;</li>
              <li>Use the Platform in any manner that may amount to hate speech, threatening, sexually explicit or pornographic, incites violence, or contains nudity or graphic or gratuitous violence;</li>
              <li>Use the Platform in any manner that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;</li>
              <li>Rent, lease, loan, trade, sell/re-sell or otherwise monetize any content or any other aspect relating to the Platform or its services, without our express permission;</li>
              <li>Solicit passwords for any purpose, or personal information for commercial or unlawful purposes from other users or disseminate another person's personal information without his or her permission;</li>
              <li>Unauthorized scraping of any information from the Platform; You can't attempt to create accounts or access or collect information in unauthorised ways. This includes creating accounts, posting or collecting information in an automated way (such as by using bots), or accessing the Platform and/or its services without our express permission;</li>
              <li>Create another account if we have already terminated your account unless you have our permission;</li>
              <li>Embed, re-publish, maintain and/or display any third-party websites/applications on any website or other internet location that ordinarily contains or hosts content that is unlawful, pornographic, obscene, defamatory, threatening, discriminatory, harassing, bullying, vulgar, indecent, profane, hateful, racially, culturally or ethnically offensive, or that encourages criminal conduct, or that gives rise, or potentially gives rise, to civil or criminal liability, or that violates any applicable laws, or that infringes or violates other parties' intellectual property rights or links to infringing or unauthorized content;</li>
              <li>Express or imply that any statements you make are endorsed by us.</li>
            </ul>
            <p className="mt-4">
              If you do or attempt any of the acts listed in Clause 9.1 and 12.1, in relation to the Platform, we may, in our sole discretion, take the following actions to protect ourselves and our community and also to comply with the applicable laws –
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>remove or block any content or information that you share on the Platform that violates these terms or any of our policies</li>
              <li>refuse to provide or stop providing any part of our services on the Platform, including complete termination of your use of the Platform;</li>
              <li>report such actions to the appropriate law enforcement authorities and commence legal proceedings against you.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">13. Registration and Securities</h3>
            <p>
              User must be registered on the Sites to access our Services. Except with SavingSathi's approval, one User may only register one member account on the Site. SavingSathi may cancel or terminate a User's account if Company has reasons to suspect that the User has concurrently registered or controlled two or more member accounts. Further, SavingSathi may reject User's application for registration for any reason. The information provided by you while availing the Services on the Website/App is subject to Privacy Policy of the Company displayed on the Website/App. The Company reserves the right to use, store, evaluate, analyze, verify, and authenticate the information and data provided by the User. User may be required to provide KYC information/details to the Company, such as electronic copies of identity proof, address proof and any other such document. You agree that you shall only use accounts owned by you, and not by any other person or entity. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the Terms of Service, We shall have the right to indefinitely suspend or terminate your account and refuse to provide You with access to the Website/App. In the event, if any discrepancy is found, in case any of the information provided by the User, for example, registration information provided does not match with the adjoining documents, such mismatch shall lead to the rejection/deactivation/termination of the registration. You acknowledge that we have the right to disclose the information (if required) provided by you to the law enforcement authorities whether or not for any investigation purposes. SavingSathi is committed to anti money laundering compliance in accordance with applicable laws and shall always prevent the use of products and services for money laundering, terror financing and other criminal activities.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">14. Registration as Vendor/Merchant</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">a)</span> To register as Vendor, You must provide your name, valid and functional e-mail addressand phone number ("Registration Data").</li>
              <li><span className="font-bold">b)</span> The Registration Data provided by you must be accurate, correct, current and true. We shallbear no liability for false, old or incorrect Registration Data provided by you. Further, you shall be liable to indemnify us against all damages, liabilities, costs and expenses that may be suffered orincurred by us as a consequence of inaccurate information provided to us by you.</li>
              <li><span className="font-bold">c)</span> You shall be solely responsible for maintaining the confidentiality of Your ID and Password and You shall be responsible for all activities that occur under Your ID and Password. We shall not be liable for any claims, damages, liabilities that may be suffered by you as a consequence of unauthorized use of your account.</li>
              <li><span className="font-bold">d)</span> You hereby expressly consent to receive communications from us through your registered phone number and/or e-mail id.</li>
              <li><span className="font-bold">e)</span> By registering for a Merchant Account, You agree to the following:
                <ul className="list-circle pl-6 mt-2 space-y-1">
                  <li>To receive communication, queries and documents from Us for the purposes ofnegotiating and executing the Merchant Agreement;</li>
                  <li>to provide information that We have a legal duty to request from a Merchant on account of the Know Your Customer norms ("KYC Norms") prescribed under RBI Regulationsand</li>
                  <li>You agree to undertake due diligence and update yourself on RBI Regulations and otherApplicable Laws that may have implications on Your Liability as a Merchant.</li>
                </ul>
              </li>
              <li><span className="font-bold">f)</span> Upon execution of Merchant Agreement, you will become a Merchant and will be entitled to services subject to these T&Cs and the Merchant Agreement.</li>
            </ul>
            <p className="mt-4">
              In the event of any inconsistency or conflict between these T&Cs and the provisions of Merchant Agreement, the provisions of the Merchant Agreement will prevail to the extent of the inconsistency or conflict.
            </p>
            <p className="mt-4">
              Merchant agrees that from time to time it shall be responsible for providing information relating to the Services proposed to be sold by the Merchant. In this connection, the Merchant undertakes that all such information shall be accurate in all respects. The Merchant shall not exaggerate or over emphasize the attributes of the Services.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">15. Conditions applicable on Merchants</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-bold">a)</span> Merchant shall be liable to offer the discount/offers/special deals, by whatever name called, to the SavingSathi registered customers, which is publicly displayed at www.SavingSathi.com &Mobile Application</li>
              <li><span className="font-bold">b)</span> Initially, all discount/offers/special deals will be valid for specific period(as decided at the time of listing)and vendors can update the same from Dash board, which will be displayed on Website/App  with the confirmation from SavingSathi within 24 Hours.</li>
              <li><span className="font-bold">c)</span> In case, vendor fails to update the offers on time, by any reason, and customer availed the offer from SavingSathiWebsite/App or through app or by any other way, merchant shall be liable to given the offer to the customers. However, Merchant can give extra benefit from the benefit listed at Website/App or application at the time of availing offer but not less than what is displayed on web/App.</li>
              <li><span className="font-bold">d)</span> Merchant will ensure to verify the SavingSathi members to offer extra benefits.</li>
              <li><span className="font-bold">e)</span> Merchant can change the rates of discount/offers/deals anytime from the vendor dashboard. Merchant may send the said changes to SavingSathi to update on the Website/App. Save as otherwise provided merchant shall provide the same offers to the customerstill the latest offers update on the Website/App.</li>
              <li><span className="font-bold">f)</span> The Merchant agrees that from time to time it shall be responsible for providing information relating to the Services proposed to be sold by them. In this connection, the Merchant undertakes that all such information shall be accurate in all respects. The Merchant shall not exaggerate or over emphasize the attributes of the Services.</li>
              <li><span className="font-bold">g)</span> SavingSathi shall not be responsible for volume of sales/customer footfall at merchant outlet.</li>
              <li><span className="font-bold">h)</span> Marchant can apply to register themselves free on web / App for their listing, which shall be live with the approval of SavingSathi Team.</li>
              <li><span className="font-bold">i)</span> SavingSathi reserves the right to refuse to activate the Vendor feature, to terminate the Vendor feature, and to remove content made available through the Vendor account at his will.</li>
              <li><span className="font-bold">j)</span> SavingSathi reserves the right to introduce and subsequently increase and/or decrease a fee for listing.</li>
              <li><span className="font-bold">k)</span> SavingSathi also reserves the right to introduce and subsequently increase and/or decrease the service fee or others, for operating the Marketplace.</li>
              <li><span className="font-bold">l)</span> SavingSathi shall notify the Vendor of such changes as provided above 30 days prior to such changes entering into force.</li>
              <li><span className="font-bold">m)</span> Continuoususes of the Marketplace for 30 days of posting of changes, as provided above, constitutes your binding acceptance of such changes.</li>
              <li><span className="font-bold">n)</span> Customized packages available for the vendors as per their requirement for their business promotions. To avail the facility, merchant may contact toSavingSathiTeam or he can promote himself by giving advertisement on our website/app by choosing multiple options available on our website/App itself</li>
              <li><span className="font-bold">o)</span> Amount paid for advertising will be non refundable except on the discretion of SavingSathi.</li>
              <li><span className="font-bold">p)</span> Flat discounts will be in MRP, not on negotiated price.</li>
              <li><span className="font-bold">q)</span> In case of discontinuation of services with us, vendors have toinform to SavingSathi in advance & till the time of delisting vendor has to offer the discounts/deals to members. Team will delist the vendor within 7 days after information from vendor.</li>
              <li><span className="font-bold">r)</span> Service provider/Merchant can change the information/details by accessing his admin panel. They can promote themselves by updating their information on the specific page provided to them.</li>
              <li><span className="font-bold">s)</span> SavingSathi can discontinue/ terminate the pages/promotions on his discretion. SavingSathi will not be liable for any loss arising from this act.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">16. CONDITIONS APPLICABLE ON CUSTOMERS/USERS.</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>By accessing SavingSathi's Website/App, you are agreeing to the terms & conditions of our company as per our privacy policy.  If you don't agree with our terms &conditions you cannot access our Website/App.</li>
              <li>Visiting the SavingSathiWebsite/App shall be considered as your consent to use your personal information as per SavingSathi's privacy policy. Provided that these policies are subject to change as per requirements of SavingSathi.</li>
              <li>In case of violation of SavingSathi terms and condition, SavingSathi has sole right to terminate the account of the user.</li>
              <li>Deals and discount provided on Website/App are subject to change as per vendor/other users. Hence customers should go through the Website/App before availing any deals.</li>
              <li>All the offers/coupons provided by company are subject to offer made by third party. Therefore, SavingSathi shall not be liable, if vendor/user is not providing the deal or discount mentioned over the Website/App. For any query and clarification customer can call or mail to our customers support executive.</li>
              <li>Content of Website/App are copyright, no one can use the content of Website/App without authorization.In case of infringement of such right necessary legal actions shall be taken against such person.</li>
              <li>SavingSathi does not make any representation or warranty as to the service and item specifics (Such as legal title, creditworthiness, identity etc.) of any of its users. SavingSathi advises to its customers to independently verify the Bonafide of any particulars.</li>
              <li>If customer wants to apply for the coupons, then he has to apply only after login to his dashboard from active coupon dashboard of digital coupons.</li>
              <li>Discount and deal cannot be utilized/ clubbed at the same time for a single transaction. SavingSathi's coupon or deal or discount cannot be clubbed or utilized with other company's product. Deals and discount cannot be clubbedexcept vendors approval & convenience</li>
              <li>The benefit of discount will be available on the MRP price of product or services not on the negotiated price decided between vendor and customer.</li>
              <li>If customer wants to negotiate first then the final price shall be lower of  following:
                <ul className="list-circle pl-6 mt-2 space-y-1">
                  <li>Discounted price negotiated between vendor and customer  or</li>
                  <li>Price arrived after deducting the discount or deal available on SavingSathi'sSite/application.</li>
                </ul>
              </li>
              <li>SavingSathi shall not be liable in any special, incidental, direct or consequential damages in connection to terms of use, even if the concerned user has informed in advance about the possibility of damages.</li>
              <li>To avail the special day deal available on Website/App , additional amount may be charged by SavingSathi.</li>
              <li>Birthday/ engagement/ Anniversary or similarly, deals are free except exclusively charge by the Website/App, and price shall be decided by SavingSathi.</li>
              <li>In the event of extra benefits offered by SavingSathi for category specific, it shall be applicable with certain terms & conditions levied by SavingSathi.</li>
              <li>SavingSathi reserves the right to amend the terms & conditions, end the offers, or call back any or all of its offers without prior notice.</li>
              <li>SavingSathi reserves the right to award offers and related benefits as per internal policy decided by SavingSathi Team from time to time.</li>
              <li>In case of dispute, SavingSathi reserves the right to resolve and take the final decision on the interpretation of these terms & conditions and fact of the dispute.</li>
              <li>Referrals: Only a registered member can get the benefit of referral amount. If a registered member refer to other person and the later person (referee) download the app and become a registered member then the referrer can get an amount as per decided by SavingSathi.</li>
              <li>When a user is connecting with other users for any deal/offer/discount then SavingSathi does not provide guarantee/assurance  about the authenticity/reliability of the other users. Still SavingSathi gets the data at the time of onboarding of the users to verify the correctness of the information as well as to check the authenticity of the member. But userhas to apply his mind/ knowledge before taking any decision.</li>
              <li>When a user provide/post any thought/opinion/suggestion/experience or share any information by hiding the identity of his own, other users those are relying on the information must apply his knowledge/ experience/mind to believe or not on the same. SavingSathi will not be responsible in any way for the authenticity, correctness and gentility of the information and also SavingSathi will not be responsible for the users if users faces any challenges/loss(direct and indirect) or any other kind of damage.</li>
              <li>Users must take necessary precautions during the posting of any offers/deals/ suggestions that should not be intentional fraudulent nature otherwise necessary legal actions will be taken against the user.</li>
              <li>SavingSathi can remove any post/deals/offers/suggestions/advertisement or any content any time showing on SavingSathi's website /application that SavingSathi thinks not fit/ appropriate/suitable for the company's or other users purposes without any notice or information to the information publisher.</li>
              <li>In case of group buying (when user buy the goods or services in bulk with other users) then in case any user face any challenge in product or service after buying the goods or services, then SavingSathi will not be responsible for any damage/loss and also not liable to compensate in any way to anyone . We are a connecting platform only where we are connecting users, vendors for their benefits. Here he has to take necessary actions or efforts to resolve the issue by connecting with other users or vendor. We are not liable for any intervention. Yes he can share his review/feedback for the future purposes so that in future, he and other users can get better services.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">17. Fees and Payment</h3>
            <p>
              The Company, at its sole discretion, reserves the right to modify the commission/fee/membership amount from time to time. Seller/Payee/Payer/Buyer ("User") shall bear and be responsible for any applicable central, state, local and foreign taxes, duties, tariffs, levies, withholdings and similar assessments (including without limitation, sales taxes, use tax, value added taxes, GST). All payments can be done online.
            </p>
            <p className="mt-4">
              Customer may pay online, offline or by any other mode as decided by the team SavingSathi
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">18. Non-working days/Blackout Days</h3>
            <p>
              SavingSathi is reliant on third parties such as Merchant/service providers/other users to deliver timely information. Since,SavingSathi cannot control the actions of such third parties; SavingSathi will not be responsible to renderServices or process payments or refunds on the following days ("Non-Working Days"):
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Days which are declared as holidays by the Government, or any other day which is a well known declared holiday.</li>
              <li>Blackout dates/ days decides by vendors or by SavingSathi team.</li>
              <li>Days including Saturdays and Sundays and declared as bandh or festivals in any State or Union Territory in India. We will continue to render Services which do not involve that particular State or Union Territory in which a bandh or festival has been declaredon that day.</li>
            </ul>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">19. Used of Site</h3>
            <p>
              Users of the website/application shall be liable to offer the discount / offers / Special Deals/benefits/information to SavingSathi's Registered Customers, which shall be published at Website/App of the company. All the offers shall be valid for a certain period which can be withdrawn by the users without the prior approval of SavingSathi. Although SavingSathi will try gradually to control over this withdrawn so that user cannot withdrawn the same without informing SavingSathi.
            </p>
            <p className="mt-4">
              In case any alteration/ changes/ variation in the offer/ rates/ discount/ deal provided by merchant shall be updated with prior approval with Team SavingSathi only.
            </p>
            <p className="mt-4">
              Merchant agrees not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Site, any transaction being conducted on the Site or any other person's use of the Site.
            </p>
            <p className="mt-4">
              The Merchant shall not make any negative, denigrating, or defamatory statement(s)/comment(s) about SavingSathi, the brand name or domain name used by SavingSathi otherwise engage in any conduct or action that might tarnish the image or reputation of SavingSathi or otherwise tarnish or dilute any trade mark, service marks, trade name and/or goodwill associated with such trade, service marks or trade name as may be owned or used by SavingSathi. The Merchant agrees that the Merchant will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site, networks, or any systems or networks connected to SavingSathi.
            </p>
            <p className="mt-4">
              Merchant can't make SavingSathi responsible for volume of sales/customer footfall at his/her outlet.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">20. Reviews, Ratings & Comments by Users</h3>
            <p>
              Since,SavingSathi provides information directory services through various mediums (SMS, WAP, E-Mail, Website/App , APP and voice or phone), your ("Users") use any of the aforementioned medium to post Reviews, Ratings and Comments about the SavingSathi services and also about the Advertiser's listed at SavingSathi is subject to additional terms and conditions as mentioned herein.
            </p>
            <p className="mt-4">
              You are solely responsible for the content of any transmissions you make to the Site or any transmissions you make to any mediums offered by SavingSathi and any materials you add to the Site or add to any mediums offered by SavingSathi, including but not limited to transmissions like your Reviews, Ratings & Comments posted by you(the "Communications"). SavingSathi does not endorse or accept any of your Communication as representative of their views. By transmitting any public Communication to the Site, you grant SavingSathi an irrevocable, non-exclusive, worldwide, perpetual, unrestricted, royalty-free license (with the right to sublicense) to use, reproduce, distribute, publicly display, publicly perform, adapt, modify, edit, create derivative works from, incorporate into one or more compilations and reproduce and distribute such compilations, and otherwise exploit such Communications, in all Platforms now known or later developed.
            </p>
            <p className="mt-4">
              You confirm and warrant that you have the right to grant these rights to SavingSathi. You hereby waive and grant to SavingSathi all rights including intellectual property rights and also "moral rights" in your Communications, posted at SavingSathi through any of mediums of SavingSathi. SavingSathi is free to use all your Communications as per its requirements from time to time. You represent and warrant that you own or otherwise control all of the rights to the content that you post as Review, Rating or Comments; that the content is accurate; that use of the content you supply does not violate these Terms and will not cause injury to any person or entity. For removal of doubts it is clarified that, the reference to Communications would also mean to include the reviews, ratings and comments posted by your Friend's tagged by you. Also SavingSathi reserves the right to mask or unmask your identity in respect of your Reviews, Ratings & Comments posted by you.
            </p>
            <p className="mt-4">
              SavingSathi has the right, but not the obligation to monitor and edit or remove any content posted by you as Review, Rating or Comments. SavingSathi cannot review all Communications made on and through any of the mediums of SavingSathi. However, SavingSathi reserves the right, but has no obligation, to monitor and edit, modify or delete any Communications (or portions thereof) which SavingSathi in its sole discretion deems inappropriate, offensive or contrary to any SavingSathi policy, or that violate this terms:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>SavingSathi reserves the right not to upload or distribute to, or otherwise publish through the Site or Forums any Communication whichis obscene, indecent, pornographic, profane, sexually explicit, threatening, or abusive;</li>
              <li>Constitutes or contains false or misleading indications of origin or statements of factslanders, libels, defames, disparages, or otherwise violates the legal rights of any third party;</li>
              <li>causes injury of any kind to any person or entity;</li>
              <li>infringes or violates the intellectual property rights (including copyright, patent and trademark rights), contract rights, trade secrets, privacy or publicity rights or any other rights of any third party;</li>
              <li>violates any applicable laws, rules, or regulations;</li>
              <li>contains software viruses or any other malicious code designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
              <li>Impersonates another person or entity, or that collects or uses any information about Site visitors.</li>
              <li>Cause the casteism or religion issue. ( Any wrong comments against the casteism and religion)</li>
            </ul>
            <p className="mt-4">
              It is also clarified that, if there are any issues or claims due to your posts by way of Reviews, Ratings and Comments, then SavingSathi reserves right to take appropriate legal action against you. Further, you shall indemnify and protect SavingSathi against such claims or damages or any issues, due to your posting of such Reviews, Ratings and Comments SavingSathi takes no responsibility and assumes no liability for any content posted by you or any third party on SavingSathi site or on any mediums of SavingSathi.
            </p>
            <p className="mt-4">
              You further acknowledge that conduct prohibited in connection with your use of the Forums includes, but is not limited to, breaching or attempting to breach the security of the Site or any of the mediums of SavingSathi.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">21. Content Disclaimer</h3>
            <p>
              SavingSathi communicates information provided and created by advertisers, content partners, software developers, publishers, marketing agents, employees, users, resellers and other third parties. While every attempt has been made to ascertain the authenticity of the content on the Platforms ,SavingSathi has no control over content, the accuracy of such content, integrity or quality of such content and the information on our pages, and material on the Platforms may include technical inaccuracies or typographical errors, and we make no guarantees, nor can we be responsible for any such information, including its authenticity, currency, content, quality, copyright compliance or legality, or any other intellectual property rights compliance, or any resulting loss or damage. Further, we are not liable for any kind of damage, losses or action arising directly or indirectly due to any content, including any errors or omissions in any content, access and/or use of the content on the Platforms or any of them including but not limited to content based decisions resulting in loss of data, revenue, profits, property, infection by viruses etc.
            </p>
            <p className="mt-4">
              All of the data on products and promotions, including but not limited to, the prices and the availability of any product or service or any feature thereof, is subject to change without notice by the party providing the product or promotion. You should use discretion while using the Platforms.
            </p>
            <p className="mt-4">
              SavingSathi reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in, any portion of the Platforms. Where appropriate, we will endeavor to update information listed on the Website/App on a timely basis, but shall not be liable for any inaccuracies.
            </p>
            <p className="mt-4">
              All rights, title and interest including trademarks and copyrights in respect of the domain name and Platforms content hosted on the Platforms are reserved with SavingSathi. Users are permitted to read, print or download text, data and/or graphics from the Website/App or any other Platforms for their personal use only. Unauthorized access, reproduction, redistribution, transmission and/or dealing with any information contained in the Platforms in any other manner, either in whole or in part, are strictly prohibited, failing which strict legal action will be initiated against such users.
            </p>
            <p className="mt-4">
              Links to external Internet sites may be provided within the content on Website/App or other Platforms as a convenience to users. The listing of an external site does not imply endorsement of the site by SavingSathi or its affiliates. SavingSathi does not make any representations regarding the availability and performance of its Platforms or any of the external Website/App s to which we provide links. When you click on advertiser banners, sponsor links, or other external links from the Website/App or other Platforms, your browser automatically may direct you to a new browser window that is not hosted or controlled by SavingSathi.
            </p>
            <p className="mt-4">
              SavingSathi and its affiliates are not responsible for the content, functionality, authenticity or technological safety of these external sites. We reserve the right to disable links to or from third-party sites to any of our Platforms, although we are under no obligation to do so. This right to disable links includes links to or from advertisers, sponsors, and content partners that may use our Marks as part of a co-branding relationship.
            </p>
            <p className="mt-4">
              Some external links may produce information that some people find objectionable, inappropriate, or offensive. We are not responsible for the accuracy, relevancy, copyright compliance, legality, or decency of material contained in any externally linked Website/App s. We do not fully screen or investigate business listing Website/App s before or after including them in directory listings that become part of the Materials on our Platforms, and we make no representation and assume no responsibility concerning the content that third parties submit to become listed in any of these directories.
            </p>
            <p className="mt-4">
              All those sections in the Platforms that invite reader participation will contain views, opinion, suggestion, comments and other information provided by the general public, and SavingSathi will at no point of time be responsible for the accuracy or correctness of such information. SavingSathi reserves the absolute right to accept/reject information from readers and/or advertisements from advertisers and impose/relax Platforms access rules and regulations for any user(s).
            </p>
            <p className="mt-4">
              SavingSathi also reserves the right to impose/change the access regulations of the Platforms, whether in terms of access fee, timings, equipment, access restrictions or otherwise, which shall be posted from time to time under these terms and conditions. It is the responsibility of users to refer to these terms and conditions each time they use the Platforms.
            </p>
            <p className="mt-4">
              While every attempt has been made to ascertain the authenticity of the content in the Platforms, SavingSathi is not liable for any kind of damages, losses or action arising directly or indirectly, due to access and/or use of the content in the Platforms including but not limited to any decisions based on content in the Platforms resulting in loss of data, revenue, profits, property, infection by viruses etc.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">22. Additional Disclaimer</h3>
            <p>
              Please remember that any provider of goods or services is entitled to register with SavingSathi. Companydoes not examine whether the advertisers are good, reputable or quality sellers of goods / service providers. You must satisfy yourself about all relevant aspects prior to availing of the terms of service. SavingSathi has also not negotiated or discussed any terms of engagement with any of the advertisers. The same should be done by you. Purchasing of goods or availing of services from advertisers shall be at your own risk.
            </p>
            <p className="mt-4">
              We do not investigate, represent or endorse the accuracy, legality, legitimacy, validity or reliability of any products, services, deals, coupons or other promotions or materials, including advice, ratings, and recommendations contained on, distributed through, or linked, downloaded or accessed from the Platforms.
            </p>
            <p className="mt-4">
              References that we make to any names, marks, products or services of third parties or hypertext links to third party sites or information do not constitute or imply our endorsement, sponsorship or recommendation of the third party, of the quality of any product or service, advice, information or other materials displayed, purchased, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the Platforms.
            </p>
            <p className="mt-4">
              Any use of the Platforms, reliance upon any Materials, and any use of the Internet generally shall be at your sole risk. SavingSathi disclaims any and all responsibility or liability for the accuracy, content, completeness, legality, reliability, or operability or availability of information or material displayed in the search results in the Platforms.
            </p>
            <p className="mt-4">
              THE MATERIAL AND THE PLATFORMS USED TO PROVIDE THE MATERIAL (INCLUDING THE WEBSITE/APP ) ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SavingSathi DISCLAIMS, TO THE FULLEST EXTENT PERMITTED UNDER LAW, ANY WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY AND PERFORMANCE OF THE PLATFORMS AND MATERIALS. SavingSathi DOES NOT WARRANT THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE CONTENT IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
            <p className="mt-4">
              SavingSathi DISCLAIMS ANY AND ALL WARRANTIES TO THE FULLEST EXTENT OF THE LAW, INCLUDING ANY WARRANTIES FOR ANY INFORMATION, GOODS, OR SERVICES, OBTAINED THROUGH, ADVERTISED OR RECEIVED THROUGH ANY LINKS PROVIDED BY OR THROUGH THE PLATFORMS SOME COUNTRIES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM COUNTRY TO COUNTRY AND JURISDICTION TO JURISDICTION.
            </p>
            <p className="mt-4">
              Users using any of SavingSathiservice across the following mediums:
              - through internet i.e.www.SavingSathi.com(Website/App ), Website, SMS, phone or any other medium are bound by this additional disclaimer wherein they are cautioned to make proper enquiry before they (Users) rely, act upon or enter into any transaction (any kind or any sort of transaction including but not limited to monetary transaction ) with the Advertiser listed with SavingSathi.
            </p>
            <p className="mt-4">
              All the Users are cautioned that all and any information of whatsoever nature provided or received from the Advertiser/s is taken in good faith, without least suspecting the Bonafide of the Advertiser/s and SavingSathi does not confirm, does not acknowledge, or subscribe to the claims and representation made by the Advertiser/s listed with SavingSathi .Further, SavingSathi is not at all responsible for any act of Advertiser/s listed at SavingSathi.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">23. Limitation of Liability</h3>
            <p>
              IN NO EVENT SavingSathi SHALL BE LIABLE TO ANY USER ON ACCOUNT OF SUCH USER'S USE, MISUSE OR RELIANCE ON THE PLATFORMS FOR ANY DAMAGES WHATSOEVER, INCLUDING DIRECT, SPECIAL, PUNITIVE, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR DAMAGES FOR LOSS OF PROFITS, REVENUE, USE, OR DATA WHETHER BROUGHT IN WARRANTY, CONTRACT, INTELLECTUAL PROPERTY INFRINGEMENT, TORT (INCLUDING NEGLIGENCE) OR OTHER THEORY, EVEN IF SavingSathi ARE AWARE OF OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, ARISING OUT OF OR CONNECTED WITH THE USE (OR INABILITY TO USE) OR PERFORMANCE OF THE PLATFORMS, THE MATERIALS OR THE INTERNET GENERALLY, OR THE USE (OR INABILITY TO USE), RELIANCE UPON OR PERFORMANCE OF ANY MATERIAL CONTAINED IN OR ACCESSED FROM ANY PLATFORMS. SavingSathi DOES NOT ASSUME ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT OR PROCESS DISCLOSED ON THE PLATFORMS OR OTHER MATERIAL ACCESSIBLE FROM THE PLATFORMS.
            </p>
            <p className="mt-4">
              THE USER OF THE PLATFORMS ASSUMES ALL RESPONSIBILITY AND RISK FOR THE USE OF THIS PLATFORMS AND THE INTERNET GENERALLY. THE FOREGOING LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. SOME COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY OF CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO ALL USERS; IN SUCH COUNTRIES LIABILITY IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">24. Indemnification</h3>
            <p>
              You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, officers, directors, agents, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of these Terms, your violation of any law, or your violation of the rights of a third party, including the infringement by you of any intellectual property or other right of any person or entity. These obligations will survive any termination of the Terms.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold mb-4 text-white">25. Miscellaneous</h3>
            <p>
              These Terms will be governed by and construed in accordance with the Indian laws, without giving effect to its conflict of law's provisions or your actual state or country of residence, and you agree to submit to personal jurisdiction in India. You agree to exclude, in its entirety, the application to these Terms of the United Nations Convention on Contracts for the International Sale of Goods. You are responsible for compliance with applicable laws. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect. These Terms constitute the entire agreement between us and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter of these Terms. Any waiver of any provision of the Terms will be effective only if in writing and signed by you and SavingSathi. Company reserves the right to investigate complaints or reported violations of these Terms and to take any action we deem necessary and appropriate. Such action may include reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties.
            </p>
            <p className="mt-4">
              In addition, we may take action to disclose any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. SavingSathi reserves the right to seek all remedies available at law and in equity for violations of these Terms.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">25.1 Notices and Communication:</h4>
            <p>
              All of our notices, demands and other communications must be in writing and will be deemed to have been given (a) if mailed by certified mail, postage prepaid, (b) if delivered by courier, (c) if sent by facsimile transmission and such transmission is confirmed as received, or (d) if sent by electronic mail, and such message is confirmed as received, in each case to the address, fax number or e-mail address specified on the Order for the recipient of such notice.
            </p>
            <p className="mt-4">
              All of your notices, demands and other communications must be in writing and will be deemed to have been given (a) if mailed by certified mail, postage prepaid or if delivered by courier, to our address: SavingSathi Global Services Private Limited, 233, Opp Sunny Trade Centre, New Aatish Market , Sanganer Jaipur- 302020.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">25.2 Force Majeure:</h4>
            <p>
              In no event shall we or any Distribution Site have liability or be deemed to be in breach hereof for any failure or delay of performance resulting from any governmental action, fire, flood, insurrection, earthquake, power failure, network failure, riot, explosion, embargo, strikes (whether legal or illegal), terrorist act, labor or material shortage, transportation interruption of any kind or work slowdown or any other condition not reasonably within our control. Your payment obligations shall continue during any event of force majeure.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Indemnification:</h4>
            <p>
              You agree to indemnify us and the Distribution Sites and hold us and the Distribution Site harmless from and with respect to any claims, actions, liabilities, losses, expenses, damages and costs (including, without limitation, actual attorneys' fees) that may at any time be incurred by us or them arising out of or in connection with these Terms or any Advertising Products or services you request, including, without limitation, any claims, suits or proceedings for defamation or libel, violation of right of privacy or publicity, criminal investigations, infringement of intellectual property, false or deceptive advertising or sales practices and any virus, contaminating or destructive features.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Telephone Conversations:</h4>
            <p>
              All telephone conversations between you and us about your advertising may be recorded and you hereby consent to such monitoring and recordation.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Conversation Records:</h4>
            <p>
              By using our services, you consent to the recording and monitoring of phone calls, video calls, messages, emails, and chat communications for quality assurance, security, and operational purposes. These records may be stored and used in accordance with our Privacy Policy.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Arbitration:</h4>
            <p>
              If any disputes and differences whatsoever arising in connection with these Terms shall be settled by Arbitration in accordance with the Arbitration and Conciliation Act, 1996.
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>All proceedings shall be conducted in English language.</li>
              <li>Arbitrator in the matter shall be the person appointed by the SavingSathi for resolution of dispute arises between the parties.</li>
              <li>The venue of Arbitration shall be in Jaipur, Rajasthan only.</li>
            </ul>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Entire Agreement:</h4>
            <p>
              These Terms constitutes the entire agreement between you and us with respect to the subject matter of these Terms and supersedes all prior written and all prior or contemporaneous oral communications regarding such subject matter. Accordingly, you should not rely on any representations or warranties that are not expressly set forth in these Terms. If any provision or provisions of these Terms shall be held to be invalid, illegal, unenforceable or in conflict with the law of any jurisdiction, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired. Except as provided in Section 1, these Terms may not be modified except by writing signed by you and us; provided, however, we may change these Terms from time to time, and such revised terms and conditions shall be effective with respect to any Advertising Products ordered after written notice of such revised terms to you or, if earlier, posting of such revised terms and conditions on our Website/App.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Severability:</h4>
            <p>
              If any part of these T&C is determined to be invalid or enforceable pursuant to Applicable Laws then the invalid or unenforceable provisions will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these T&Cs will continue in effect.
            </p>

            <h4 className="text-lg font-bold mt-6 mb-3 text-white">Brand Usage:</h4>
            <p className="pb-25">
              We do not permit anyone to generate additional income by using our brand name or promoting it without a formal contract in place. No individual is allowed to use our brand name to earn extra revenue or benefits without prior notification and approval from us. In case, anyone does that, legal action can be taken against them.
            </p>
          </div>
        </div>
      </div>
    </section>
    </>);
};

export default termsAndConditions;