import React from "react";
import bg3 from "../../../assets/home/bg-3.jpg";
import Head from "next/head";

const PrivacyPolicy: React.FC = () => {
  return (<>
    <Head>
    <title>Our Privacy Policy | SavingSathi App</title>
    <meta 
      name="description" 
      content="Read the SavingSathi privacy policy to understand how we handle your data, ensure security, manage permissions, and protect your personal information." 
    />
    
    <meta property="og:title" content="Our Privacy Policy | SavingSathi App" />
    <meta 
      property="og:description" 
      content="Read the SavingSathi privacy policy to understand how we handle your data, ensure security, manage permissions, and protect your personal information." 
    />
    <link rel="canonical" href="https://savingsathi.com/privacy-policy" />
  </Head>
    <section className="bg-black text-white min-h-screen">
      {/* Header */}
      <div
        className="w-full h-70 flex justify-center items-center bg-cover bg-center relative"
        style={{
            backgroundImage:`url(${bg3.src})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundAttachment: "fixed"
          }}
      >
        <h1 className="text-4xl font-extrabold text-center tracking-wider z-10">
          <span className="text-white">PRIVACY &amp; </span>
          <span className="bg-gradient-to-r from-rose-600 to-cyan-700 bg-clip-text text-transparent">POLICY</span>
        
        </h1>
        {/* Overlay for dark effect */}
        {/* <div className="absolute inset-0 bg-black opacity-70"></div> */}
      </div>

      {/* Content */}
      <div className="max-w-6xl mx-auto mt-16 md:px-0">
        <p className="mb-6 text-gray-300 text-sm leading-relaxed">
          The SavingSathi platform is made available by SavingSathi Global Services Private Limited
          (&quot;our&quot;, &quot;us&quot;, &quot;we&quot;, &quot;Company&quot;), having its registered
          office at - 233, Opp Sunny Trade Centre, New Aatish Market, Sanganer Jaipur- 302020,
          India. We recognise that your privacy is very important and take it seriously. To provide you
          with access to our platform, we need to collect various data and information from you. This
          Privacy Policy (&quot;Policy&quot;) details how this data and information is collected,
          retained, shared, stored, and processed by us. This policy incorporates and includes our
          Terms of Use. Words and phrases not defined in this policy shall have the same meaning as
          provided in the Terms of Use.
        </p>
        <p className="mb-10 text-gray-300 leading-relaxed">
          By using this platform, you agree to the terms and conditions of this Privacy Policy
          (&quot;Policy&quot;) and any updates to it. If you do not agree with any part of this policy,
          please stop using our platform immediately.
        </p>

        <h2 className="text-xl font-bold mb-4">1. Information we collect</h2>
        <p className="mb-6 text-gray-300 leading-relaxed">
          We collect the data you provide only to ensure that we can provide you access to our platform
          in the best manner possible.
        </p>

        <h3 className="font-semibold mb-2">(A) Data you input.</h3>
        <p className="mb-6 text-gray-300 leading-relaxed">
          We collect the information that you actively enter into the platform:
        </p>

        <p className="mb-6 text-gray-300 leading-relaxed">1. SavingSathi Account data: We collect the data you provide us when you create or update your SavingSathi Account. This includes your phone number, phonebook, email id, personal details (like Passport, PAN card, AADHAR card and such other documents and information that may be required from time to time including your name, address including postcodes, date of birth ) , profession, area of interest etcand any information provided therein by you. We may require you to share further data at a later date to confirm the veracity of your information or under any additional features added to the platform.</p>
        <p className="mb-6 text-gray-300 leading-relaxed">2. Feedback and other data: We collect and record: (i) any emails you write to us; (ii) the calls you make to our call centres and/or customer service personnel; and (iii) feedback or comments you provide to us on the Platform, including any crash reports and log reports generated by you.</p>
        <p className="mb-6 text-gray-300 leading-relaxed">3. Details of accounting or financial transactions including transactions carried out through the Site or otherwise. This may include information such as your credit card, debit card or bank account details etc.</p>

        <h3 className="font-semibold mb-2">(B) Location and Contacts.</h3>
        <p className="mb-6 text-gray-300 leading-relaxed">We require the following accesses to improve your user experience while ensuring anonymity and connection with other users:</p>
        <p className="text-gray-300 leading-relaxed">1. Location: We use your location to provide you with posts and updates from around your location.
        </p>
        <p className="text-gray-300 leading-relaxed">2. Contacts: We use them to show you posts that are posted by people in your contact list. They won’t know that you’re here. Keeping it even, you won’t know who they are, just their posts. It’s just to help you to show the post made by your known one.</p>
        <h3 className="font-semibold mb-2">(C) Data collected from your use.
        </h3>
        <p className="text-gray-300 leading-relaxed">We collect the following data generated while you use the Platform:</p>
        <p className="text-gray-300 leading-relaxed">1. Platform usage data: We collect data on your interaction with our platform, i.e., platform access dates and times, features or pages viewed, crashes and other system activity like posts, comments, likes, shares, advertisements, tags, chats and type of browser used to access the platform, and third- party sites or services used before or in the course of interacting with our platform.</p>
      <p className="text-gray-300 leading-relaxed">2. Content You Submit: We gather the content you provide to our platform, which encompasses your posts, comments, chats, feedback, reviews as well as your reports and any other communications with us. Your content may comprise text, links, images, gif and video.</p>
      <p className="text-gray-300 leading-relaxed">3. Device data: We may collect data about the devices used to access our platform, including the hardware models, device IP address, operating systems and versions, software, preferred languages, unique device identifiers, serial numbers, browser type, mobile app, file names and types, and plugins.</p>
      <p className="text-gray-300 leading-relaxed">4. Cookies, log files, web beacons and tracking pixels: We also collect information through the use of “cookies”, “log files”, “web beacons” and “tracking pixels”, and similar technologies to understand how you navigate through the platform to learn your preferences. Cookies are small text files that web servers place on your device; they are designed to store basic information and to help websites and apps recognize your browser. We may use both session cookies and persistent cookies. A session cookie disappears after you close your browser. A persistent cookie remains after you close your browser and may be accessed every time you use the Platform. Log files track actions that occur on our platform and collect data including your IP address, browser type, internet service provider, referring and exit pages, and the date and time stamps. Web beacons, tags and pixels are electronic files used to record information about how you browse the platform.</p>
      <p className="text-gray-300 leading-relaxed">5. Location : We take location information to provide you with the best-localized experience, so users can relate to the timeline.</p>

      <h3 className="font-semibold mb-2">(D) Information received from third parties.</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We may also be working closely with third parties (including, for example, business partners, technical sub-contractors, analytics providers such as Google Analytics) and may receive information about you from such sources. If you link your account with social media platforms, we may receive information about you from such platforms. Such data may be shared internally and combined with data collected under Section 1.1 and 1.2 above. Please note that we do not control what these third-parties do with your personal data. Their activities are not covered under this Policy. They would be covered by their respective privacy policies. It is such third-parties’ responsibility to ensure that your consent was duly taken by them for sharing your personal data or information. We are not liable for their acts or omissions, in any manner whatsoever.We may also be working closely with third parties (including, for example, business partners, technical sub-contractors, analytics providers such as Google Analytics) and may receive information about you from such sources. If you link your account with social media platforms, we may receive information about you from such platforms. Such data may be shared internally and combined with data collected under Section (A) and (B) above. Please note that we do not control what these third-parties do with your personal data. Their activities are not covered under this Policy. They would be covered by their respective privacy policies. It is such third-parties’ responsibility to ensure that your consent was duly taken by them for sharing your personal data or information. We are not liable for their acts or omissions, in any manner whatsoever.
        </p>

        <h2 className="font-semibold mb-2">2. Use of collected data
        </h2>
        <p className="text-gray-300 leading-relaxed mb-6">
        The data we collect from you will be used for the following purposes:
        </p>

        <h3 className="font-semibold mb-2">(A) For enabling the Platform.</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We use the data collected to operate, personalize, maintain and improve our platform. This includes using the data to
        </p>

        <p className="text-gray-300 leading-relaxed mb-6">1. Create and update your SavingSathi Account: Upon signing on to the platform we will create your profile/account based on the information submitted by you, which can be changed once your account is created. Here you can change /edit your information as well as the user name that you want to show to public . We use your phone number and/or other data you share to verify your account.
</p>
<p className="text-gray-300 leading-relaxed mb-6">2. Perform internal operations necessary to provide you and improve our platform, including troubleshooting software bugs and operational problems;</p>
<p className="text-gray-300 leading-relaxed mb-6">3. conduct data analysis, testing, and research; and to monitor and analyse usage and activity trends.</p>
<p className="text-gray-300 leading-relaxed mb-6">4. Enable platform features including those relating to content visibility. We may access your phonebook to connect you to your existing contacts who are also on the platform. We may also use this information to better recommend content to you and your contacts, for e.g. while browsing your timeline your connection’s posts will be visible first.</p>
<p className="text-gray-300 leading-relaxed mb-6">5. Assist in making general improvements to the Site, allow you to participate in features of the Site and other services,collect payments from you,ensure that you comply with the Conditions and applicable law etc.</p>
<p className="text-semibold">(B) For enabling customer support and communication, we use the information to provide customer support and train our customer service executives. We may further add features that allow you to call us (through the platform or otherwise), similarly, we may also need to contact you through the platform.</p>
<p className="text-semibold">(C) For marketing and outreach, we use the data we collect to market our platform. This includes sharing your feedback, ratings and screen names for purely promotional and marketing purposes. Such promotion and marketing may be done via hoardings, banners, pamphlets etc.</p>
<p className="text-semibold">(D) For fraud detection and preventing misuse, we use the data we collect to detect fraudulent usage of the platform and/or misuse of any of the features of the platform.</p>
<p className="text-semibold mb-2">(E) For legal compliance and requirements, we use the data we collect to address claims or disputes relating to the use of our platform, or as otherwise allowed by applicable law, or as requested by regulators, government entities, and official inquiries.</p>

        
        
        

        <h2 className="text-xl font-bold mt-10 mb-4">3. Sharing of data</h2>
        <p className="text-gray-300 leading-relaxed mb-4">We do not share any personal data about you with any third parties unless necessary. We may enter into agreements or arrangements to enable the use of our platform.We only collect such information when you choose to supply it to us. You do not have to supply any personal information to us but you may not be able to take advantage of all the services we offer without doing so. We have detailed how we share the collected data below:</p>
        <p className="text-gray-300 leading-relaxed">(a) When on your post, someone is interested and wants to connect with you, then for better connection and understanding, we may share limited information about you to the other users like other review’s on your profile, interest, email id etc.</p>
        <p className="text-gray-300 leading-relaxed">(b) If sharing is important for better and fast servicewe may transfer your personal information to a third party as part of a sale of some or all of our business and assets to any third party or as part of any business restructuring or reorganisation, but we will take steps with the aim of ensuring that your privacy rights continue to be protected.</p>
        <p className="text-gray-300 leading-relaxed">(c) for the purpose of verification by third party service providers of the information contained in the IDs and other documents that may be collected from the Members at the time of registration or at any other time during their use of the Site as may be required. Third party service providers will process data under SavingSathi’s control and will be bound by the same degree of security and care as SavingSathi’s under this Privacy and Data Protection Policy.
        </p>
        <p className="text-gray-300 leading-relaxed">(d) for the purpose of maintaining internal quality, training and updating the customers about the Services of SavingSathi.</p>



        <h3 className="font-semibold mb-2">(A) Service Providers</h3>

        <p className="text-gray-300 leading-relaxed mb-4">
        We work with third-party service providers to execute various functionalities of the platform, and we may share your information with such service providers to help us provide you with our services on the platform.
        </p>

        <p className="text-gray-300 leading-relaxed mb-4">You may allow access to your phone contact list which will only be used to enhance your experience on the SavingSathi app. The contact list information will help the platform to provide you with an updated feed from your contacts. Enabling access to your contact list will allow you to see what your contacts on SavingSathi share and vice-versa.</p>

        <h3 className="font-semibold mb-2">(B) Group Companies or Change in Control.</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We may share your personal data with any member of our Group. The term "Group" shall mean any entity that is controlled by us, or any entity that is in control of us, or any entity that is under common control with us, whether directly or indirectly. While negotiating or about a change of corporate control such as a restructuring, merger or sale of our assets, we may have to disclose our databases and information we have stored in the course of our operations.
        </p>

        <h3 className="font-semibold mb-2">(C) Law Enforcement.</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We may disclose and otherwise use your personal and other information where we or they reasonably believe such disclosure is needed to: satisfy any applicable law, regulation, legal process, or governmental request,enforce applicable terms of use, including investigation of potential violations thereof, detect, prevent, or otherwise address illegal or suspected illegal activities (including payment fraud), security or technical issues, protect against harm to our rights, property or safety, our users or the public, as required or permitted by law.
        </p>
        <p className="text-gray-300 leading-relaxed mb-6">
        Any personal information, including but not limited to mobile number, phone number, email, name, addresses, bank or card details, shared by you that belongs to another individual is subject to applicable laws and may be disclosed to law enforcement authorities as required by law. Additionally, we reserve the right to share your personal or profile information with other social media platforms or third-party entities in accordance with our privacy policy and applicable laws and regulations. SavingSathi community guidelines!
        </p>
        <p className="text-gray-300 leading-relaxed mb-6">
        Here are the "Don'ts" to keep in mind- a. Do not share someone's personal information on the platform; b. Do not post, share or engage in content that is threatening or promotes discrimination; c. Do not engage in or create abusive content; d. Do not post or share vulgar or explicit content.
        </p>
        <p className="text-gray-300 leading-relaxed mb-6">
        "Our content moderation team reviews the reported content and if we find anything that goes against our guidelines. Your post will be deleted, and your account may be suspended"
        </p>

        <h3 className="text-semibold mb-3">4. Consent</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        By setting up a SavingSathi Account, you agree to our processing, storage, usage, and sharing of data provided by you under this Policy. If you do not agree with any of the terms of this policy or the Terms of Use or wish to revoke any consent you have provided to us, please write to us at support@SavingSathi.com. However, if you revoke any mandatory permissions then we may have to cease providing you with access to the Platform and services therein.
        </p>
        <h3 className="text-semibold mb-3">5. Your Rights</h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        It is important to us that you remain in control of your data. Please write to us support@SavingSathi.com if you wish to exercise any of your rights provided below:
        </p>
        <p className="text-gray-300 leading-relaxed mb-4">
        (a) Right to rectification. If any personal data provided by you is inaccurate, incomplete or outdated, then you shall have the right to provide us with accurate, complete and up to date data and have us rectify such data at our end immediately. We urge you to ensure that you always provide us with accurate and correct information to ensure that your use of our platform is uninterrupted.
        <br/>
(b) Right to erasure. You have the right to demand us to erase your data and we will do so without undue delay, provided that the data is no longer required by us and there is no legal requirement to retain the data. Do note that multiple legal bases may exist in parallel and we may still have to retain certain personal data at any time, despite your request to delete it. We may not be able to provide you with our services and access to the platform, once your personal data is deleted.
<br/>
(c) Right to confirmation and access. You can seek confirmation from us as to whether any of your data is being or has been processed. If we are processing such data, then you may ask us for a summary of such processed data. You also have the right to ask us for a summary of our processing activities.
<br/>
(d) Right to opt-out. You may opt-out of receiving promotional and marketing emails from us by writing to us. You may also opt-out of receiving emails and other messages from us by following the unsubscribe instructions in those messages. Please note that opting out of receiving push notifications may impact your use of the platform. However, even if you opt-out of receiving our promotional and marketing emails, we will still send you transactional messages through emails that may be required during your use of the platform.
        </p>

        <h3 className="font-semibold mb-2">6. Data retention
        </h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We shall retain the information you provide to facilitate smooth and uninterrupted use of the platform and to: 6.1. provide, improve and personalize our platform; 6.2. to contact you about your SavingSathi account and provide you with customer service; 6.3. to personalize our marketing communications; 6.4. to prevent, detect, mitigate, and investigate fraudulent or illegal activities; and 6.5. to comply with applicable laws, including any data retention and storage requirements that may be provided under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. Our endeavour is to immediately act on your request for deletion, and we strive that we do not retain your data for longer than required for the purpose for which the information may be lawfully used. However, there is a possibility that copies of any public content may be retained indefinitely in our systems, including in cached and archived pages of the platform, or if other users have copied or saved that information.
        </p>
        <h3 className="font-semibold mb-2">7. 7. Changes to the Policy
        </h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We may periodically update this Privacy Policy. Whenever we make any changes to this Privacy Policy we will post the updated Privacy Policy at this link. It is your responsibility to keep checking this page from time to time in order to be aware of any changes made to this Policy. By continuing to access or use the platform and/or our services after those changes become effective, you agree to be bound by the revised Privacy Policy.
        </p>

        <h3 className="font-semibold mb-2">8. Cross border data transfer
        </h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        Your data held by us may be transferred to other countries outside your residential country for any of the purposes described in this policy. You understand and accept that these countries may have differing (and potentially less stringent) laws relating to the degree of confidentiality afforded to the information it holds and that such information can become subject to the laws and disclosure requirements of such countries, including disclosure to governmental bodies, regulatory agencies and private persons, as a result of applicable governmental or regulatory inquiry, court order or another similar process. In addition, several countries have agreements with other countries providing for the exchange of information for law enforcement, tax and other purposes. If we transfer your data to third parties for purposes stated in this Policy, we will use best endeavours to put in place appropriate controls and safeguards to ensure that your data is kept accurate, adequately protected, and processed only for specified and reasonable purposes in a manner that is fair, transparent and has a lawful basis, and is stored for no longer than is necessary.
        </p>
        <h3 className="font-semibold mb-2">9. Data security
        </h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We use appropriate technical and organizational security measures to ensure the protection of your data. The transfer of personal data between your end device and us is generally carried out in an encrypted form (TLS encryption). You can identify an encrypted connection for example by the lock symbol in the address line of your browser. If you communicate with us by email, access by third parties cannot be ruled out. However, remember that no method of transmission over the internet, or method of electronic storage is entirely secure and reliable, and we cannot guarantee its absolute security.
        </p>

        <h3 className="font-semibold mb-2">10. Communications from us </h3>
        <p className="text-gray-300 leading-relaxed mb-6">
        We may from time to time send you Platform-related announcements in your interest, whenever necessary. This includes communications via text messages, push notifications on your computer or mobile device, or by posting notices on the Platform. We will also share with you periodical reminders to comply with the Terms of Use and this Policy, including any updates (wherever applicable).
        </p>
        <h3 className="font-semibold mb-2">11. Grievances and redressal
        </h3>
<p className="text-gray-300 leading-relaxed mb-6">
We are committed to promptly addressing any grievances that you might have in connection with our use of any information that you provide to us. Accordingly, you may communicate any grievance that you might have by emailing us at support@savingsathi.com. Please note that if you contact us to assist you, for your safety and ours, we may need to authenticate your identity before fulfilling your request.
</p>
       
       <h3 className="font-semibold mb-2">12. Policies for Posts Boost </h3>
       <p className="text-gray-300 leading-relaxed mb-6">
       On our platform, we offer users the opportunity to boost their posts to increase their reach and engagement. However, ensuring that the boosted posts align with our community guidelines and promote a safe and inclusive environment for all users is important.
</p>
<p className="text-gray-300 leading-relaxed mb-6">
(a) Offensive Content: Posts that include hate speech, threats, harassment, or any form of offensive language are not eligible for boosting. This includes content that promotes violence, discrimination, or harm towards individuals or groups based on attributes such as race, ethnicity, religion, gender, sexual orientation, disability, or any other protected characteristic.
<br/>
(b) Sexual Content: Posts that contain explicit or adult content, including nudity, sexual acts, or sexually suggestive material, cannot be boosted. Any content that promotes or facilitates sexual exploitation, trafficking, or non-consensual activities is strictly prohibited.
<br/>
(c) Discriminatory Content:Posts that discriminate against individuals or groups based on race, ethnicity, religion, gender, sexual orientation, disability, or any other protected characteristic are not eligible for boosting. We value inclusivity and diversity, and we will not support or promote content that promotes discrimination, prejudice, or stereotypes.
<br/>
(d) Communal Harm: Posts that incite violence, encourage self-harm, or promote dangerous activities that pose a risk to individuals or communities are strictly prohibited from being boosted. Any content potentially harming individuals, communities, or public safety is not eligible for boosting.
<br/>
(e) Review Process: All boosted posts will go through a review process to ensure compliance with the above policies. Our team will review each boosted post to verify its eligibility and adherence to our guidelines. In the event that a post is found to violate any of the policies, it will be rejected from the boosting process. Consequences of Policy Violation: Users found violating the post-boost policy may face penalties, including but not limited to post-removal, and temporary or permanent suspension of boosting privileges. We reserve the right to take appropriate action based on the severity and frequency of policy violations. Note: This policy aims to create a safe and respectful environment for all users. We encourage users to report any content that violates our policies to help us maintain a positive community.
</p>

       

        <h3 className="font-semibold mb-4">13. Cookies</h3>
        <p className="text-gray-300 leading-relaxed mb-20">
        (a) A cookie is a piece of data stored locally on your computer and contains information about your activities on the Internet. The information in a cookie does not contain any personally identifiable information you submit to our site.
        <br/>
(b) On the Site, we use cookies to track users’ progress through the Site, allowing us to make improvements based on usage data. We also use cookies if you log in to one of our online services to enable you to remain logged in to that service. A cookie helps you get the best out of the Site/App and helps us to provide you with a more customised service.
<br/>
(c) Once you close your browser, our access to the cookie terminates. You have the ability to accept or decline cookies. Most web/app browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. To change your browser settings you should go to your advanced preferences.
<br/>
(d) We have a clear cookies notice on the home page of the website as well as we get consent at when you register yourself on the application. If you continue to use the Site/application having seen the notice then we assume you are happy for us to use the cookies described above.
<br/>
(e) If you choose not to accept the cookies, this will not affect your access to the majority of information available on the Site/Application. However, you will not be able to make full use of our online services.
        </p>



        

      </div>
    </section>
    </>);
};

export default PrivacyPolicy;
